# Configuration
LineLength:
  Max: 100

# Exclude certain files
ClassAndModuleChildren:
  Exclude:
    - db/seeds.rb

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true