require "minitest/autorun"
require "minitest/pride"
require "pry"

require "./lib/item"
require "./lib/gilded_rose"
require "./lib/normal_item"
require "./lib/aged_brie"
require "./lib/sulfuras"
require "./lib/conjured"
require "./lib/back_stage_pass"
